public enum EquipmentStatType
{
    MaximumHealth,
    Armor,
    Evasion,
    HealthRegen,
    Damage,
    AttackSpeed,
    Range,
    MovementSpeed,
    PickupRange,
    Knockback,
    ShrineQuantity,
    EnemyQuantity,
    EnemyQuality,
    MapDropChance,
    EquipmentDropChance,
    ExperienceGain,
}
