public enum EquipmentStatType
{
    MaximumHealth = 0,
    Armor = 1,
    Evasion = 15,
    Barrier = 16,
    HealthRegen = 2,
    Damage = 3,
    AttackSpeed = 4,
    Range = 5,
    MovementSpeed = 6,
    PickupRange = 7,
    Knockback = 8,
    ShrineQuantity = 9,
    EnemyQuantity = 10,
    EnemyQuality = 11,
    MapDropChance = 12,
    EquipmentDropChance = 13,
    ExperienceGain = 14,
    CriticalChance = 17,
    CriticalDamage = 18,
}
